import Foundation
import SwiftUI

/// Idioma da interface (Setup A-01). O LookinBody original tem 26 idiomas; aqui os que
/// interessam à clínica: Português (Brasil) e o Inglês de origem.
///
/// A CHAVE da tradução é o próprio texto em inglês: assim nada quebra se faltar uma entrada
/// (cai no inglês) e não existe chave inventada para manter sincronizada.
enum Idioma: String, CaseIterable, Identifiable {
    case ptBR = "Portuguese(Brazil) [BR]"
    case enGB = "English [GB]"
    var id: String { rawValue }

    static let chaveDefaults = "InBodyMac.idioma"

    static var atual: Idioma {
        get { Idioma(rawValue: UserDefaults.standard.string(forKey: chaveDefaults) ?? "") ?? .ptBR }
        set { UserDefaults.standard.set(newValue.rawValue, forKey: chaveDefaults) }
    }

    /// Formato de data padrão do idioma (0 Ano.Mês.Dia · 1 Mês.Dia.Ano · 2 Dia.Mês.Ano).
    /// Português (Brasil) = Dia.Mês.Ano; Inglês = Mês.Dia.Ano.
    var padraoFormatoData: Int {
        switch self {
        case .ptBR: return 2
        case .enGB: return 1
        }
    }

    static var padraoFormatoData: Int { atual.padraoFormatoData }
}

/// Traduz um texto da interface. `en` é o texto em INGLÊS = a chave canônica.
/// Inglês é o idioma-base (sem dicionário → devolve a própria chave). Cada outro idioma
/// tem seu dicionário em `dicionarios`. Adicionar um idioma no futuro = novo case no enum
/// Idioma + uma entrada aqui; nada mais muda.
func T(_ en: String) -> String {
    guard let dic = dicionarios[Idioma.atual] else { return en }   // inglês (base) cai aqui
    return dic[en] ?? en                                            // faltou tradução → inglês
}

/// Tabela de idiomas → dicionário. Inglês não entra (é a base).

/// Overrides de INGLÊS: só troca a marca (InBody/LookinBody) por termo neutro; o resto
/// cai na própria chave (inglês-base). Assim o programa em inglês não exibe marca de terceiros.
private let traducaoEN: [String: String] = [
    "* Click [InBody] under Health Report to view detailed results.": "* Click [Body Composition] under Health Report to view detailed results.",
    "* If the InBody Test was taken without age or gender, results cannot be saved — only member information will be saved.": "* If the Body Composition Test was taken without age or gender, results cannot be saved — only member information will be saved.",
    "* InBody results cannot be added here (only ID and date are editable).": "* Body Composition results cannot be added here (only ID and date are editable).",
    "* The restored data from LookinBody will be merged with your current data.": "* The restored data from this app will be merged with your current data.",
    "* When connected to the InBody, information will automatically save in LookinBody.": "* When connected to the scale, information will automatically save in this app.",
    "01. InBody Model": "01. Scale Model",
    "02. InBody data integration": "02. data integration",
    "03. InBody Results Sheet integration": "03. Body Composition Results Sheet integration",
    "07. Import Data from Previous LookinBody": "07. Import Data from a Previous Version",
    "1) Click [Data Importation] below.  2) Select the USB used to export data from the InBody. Open the 'inbody' folder, then select the 'lookinbody' folder.": "1) Click [Data Importation] below.  2) Select the USB used to export data from the scale. Open the 'inbody' folder, then select the 'lookinbody' folder.",
    "1. Convert results in LookinBody to image/CSV and save to your destination folder.  2. Results in the folder are available for use in EMR.": "1. Convert results in the app to image/CSV and save to your destination folder.  2. Results in the folder are available for use in EMR.",
    "1. Input data in the provided LookinBody Excel file.": "1. Input data in the provided Excel template.",
    "1. Set up a Cloud Service.  2. After setup, log in to your LookinBody Web account.": "1. Set up a Cloud Service.  2. After setup, log in to your cloud account.",
    "4. Print Results Sheets automatically after each InBody Test.": "4. Print Results Sheets automatically after each Body Composition Test.",
    "Connect InBody": "Connect scale",
    "Connecting to the InBody…": "Connecting to the scale…",
    "Convert results automatically to CSV files after each InBody Test?": "Convert results automatically to CSV files after each Body Composition Test?",
    "Convert results automatically to an image file after each InBody Test?": "Convert results automatically to an image file after each Body Composition Test?",
    "Detailed integration methods are provided in a separate manual. LookinBody120 is a local PC program and does not provide a dedicated server.": "Detailed integration methods are provided in a separate manual. This app is a local PC program and does not provide a dedicated server.",
    "Explanation of the InBody Test results.": "Explanation of the Body Composition Test results.",
    "Failed to connect. The InBody Test cannot begin.\\n* Click 'Troubleshooting' on bottom for help.": "Failed to connect. The Body Composition Test cannot begin.\\n* Click 'Troubleshooting' on bottom for help.",
    "Health Report : InBody": "Health Report",
    "Import Data from Previous LookinBody": "Import Data from a Previous Version",
    "Import Data from past versions of LookinBody to LookinBody120.": "Import data from past versions into this app.",
    "Import data saved from the InBody by using the USB Thumb Drive.": "Import data saved from the scale by using the USB Thumb Drive.",
    "InBody": "Body Composition",
    "InBody Children's Result Sheet": "Children's Result Sheet",
    "InBody Paper": "Preprinted Paper",
    "InBody Result Interpretation": "Body Composition Result Interpretation",
    "InBody Result Sheet": "Body Composition Result Sheet",
    "InBody Score Output": "Body Composition Score Output",
    "InBody Test": "Body Composition Test",
    "InBody Test Completed": "Body Composition Test Completed",
    "InBody Test Date": "Test Date",
    "InBody Test Settings": "Body Composition Test Settings",
    "InBody Test completed.": "Body Composition Test completed.",
    "InBody account": "cloud account",
    "InBody account unavailable in this installation (feature not generated).": "cloud account unavailable in this installation (feature not generated).",
    "InBody\\nTest": "Body Composition\\nTest",
    "LookinBody  →  Folder  →  EMR": "This app  →  Folder  →  EMR",
    "LookinBody Data Management": "Data Management",
    "LookinBody Website Account Login": "Cloud Account Login",
    "LookinBody120 configuration screen. Options are saved with the button below.": "App configuration screen. Options are saved with the button below.",
    "Output = a result of the InBody Test. Interpretation = an explanation of the output. Bracketed values [n] show required space.": "Output = a result of the Body Composition Test. Interpretation = an explanation of the output. Bracketed values [n] show required space.",
    "Register a group of members by importing a batched group from the provided LookinBody Excel file.": "Register a group of members by importing a batched group from the provided Excel template.",
    "Remember to back up data when planning to re-format, transfer data, or remove/reinstall LookinBody.": "Remember to back up data when planning to re-format, transfer data, or remove/reinstall the app.",
    "Restore InBody Default": "Restore Default",
    "Restore data from a previous LookinBody backup file.": "Restore data from a previous backup file.",
    "Save InBody result into My PC": "Save Body Composition result into My PC",
    "Saved (InBody account).": "Saved (cloud account).",
    "Search by InBody Test Date": "Search by Test Date",
    "Select outputs/interpretations to print on the right side of the InBody Results Sheet, or shown as Body Composition History graphs on the Health Report.": "Select outputs/interpretations to print on the right side of the Body Composition Results Sheet, or shown as Body Composition History graphs on the Health Report.",
    "Select the InBody model.": "Select the scale model.",
    "Shows InBody Test results with graphs.": "Shows Body Composition Test results with graphs.",
    "Start the InBody Test immediately after registration.": "Start the Body Composition Test immediately after registration.",
    "Step barefoot on the InBody and stay still.": "Step barefoot on the scale and stay still.",
    "Step barefoot on the InBody to begin.": "Step barefoot on the scale to begin.",
    "The InBody model can be changed.": "The scale model can be changed.",
    "To reinstall LookinBody, the install files and any saved data must be on a USB Thumb Drive. The provided Hardlock Key must also be plugged into the computer.": "To reinstall the app, the install files and any saved data must be on a USB Thumb Drive. The provided Hardlock Key must also be plugged into the computer.",
    "• Check that the InBody is on the same network and powered on.\\n• Confirm the InBody model and interface under Setup.\\n• Always connect a Blood Pressure Monitor from InBody.": "• Check that the scale is on the same network and powered on.\\n• Confirm the scale model and interface under Setup.\\n• Always connect a compatible Blood Pressure Monitor.",
]

private let dicionarios: [Idioma: [String: String]] = [
    .ptBR: traducaoPTBR,
    .enGB: traducaoEN,
]

/// pt-BR das telas. Termos clínicos seguem a folha de resultado da própria InBody
/// (Massa Muscular Esquelética, Porcentual de Gordura, Taxa de AEC...).
private let traducaoPTBR: [String: String] = [
    // ==== itens 1 e 3 (telas menores + folhas nativas) 15/08/2026 ====
    "No folder linked. Click Connect and choose your cloud folder.": "Nenhuma pasta vinculada. Clique em Conectar e escolha a pasta da sua nuvem.",
    "The linked folder no longer exists:": "A pasta vinculada não existe mais:",
    "Could not write to": "Não consegui gravar em",
    "This clinic's backup was sent to the cloud folder.": "Backup desta clínica enviado para a pasta da nuvem.",
    "Link the cloud folder first.": "Vincule a pasta da nuvem primeiro.",
    "Database unavailable.": "Banco indisponível.",
    "No backup in the folder yet. Ask the other clinic to send theirs.": "Nenhum backup na pasta ainda. Peça à outra clínica para enviar o dela.",
    "Merged": "Juntei",
    "record(s) and": "cadastro(s) e",
    "exam(s) from": "exame(s) de",
    "backup(s).": "backup(s).",
    "joined by ID.": "unido(s) pelo ID.",
    "Access reader tool not found.": "Ferramenta de leitura Access não encontrada.",
    "No exam found in the file.": "Nenhum exame encontrado no arquivo.",
    "Imported": "Importados",
    "patients and": "pacientes e",
    "exams.": "exames.",
    "Set up email in Settings > E-mail Options.": "Configure o e-mail em Configurações > E-mail Options.",
    "Could not reach the email server:": "Não consegui falar com o servidor de e-mail:",
    "The email server refused:": "O servidor de e-mail recusou:",
    "Feature not built yet": "Função ainda não construída",
    "The button": "O botão",
    "is not available in OpenBody yet. Nothing was done.": "ainda não está disponível no OpenBody. Nada foi feito.",
    "09. Merge patients from different clinics": "09. Unificar pacientes de clínicas diferentes",
    "Server saved. Emails will now go through it.": "Servidor salvo. Os e-mails passarão a sair por ele.",
    "Missing host, user, or password (leave blank to use your Mac Mail).": "Faltou host, usuário ou senha (deixe em branco para usar o Mail do seu Mac).",
    "Email sending": "Envio de e-mail",
    "By default, OpenBody opens your Mac email app with the exam already attached. Just click Send. Nothing to configure.": "Por padrão, o OpenBody abre o app de e-mail do seu Mac com o exame já anexado. É só clicar em Enviar. Não precisa configurar nada.",
    "Prefer your own server (SMTP)? Fill in below (optional).": "Prefere usar o seu próprio servidor (SMTP)? Preencha abaixo (opcional).",
    "Login screen on app launch": "Tela de login ao abrir o app",
    "If on, the app asks for login every time it opens. (Takes effect next launch.)": "Se ligado, o app pede login toda vez que abrir. (Vale a partir da próxima abertura.)",
    "Example (sheet not ported yet)": "Exemplo (folha ainda não portada)",
    "Print alignment": "Alinhamento da impressão",
    "Offset in mm (max ±10). Positive = right / down.": "Deslocamento em mm (máx. ±10). Positivo = direita / para baixo.",
    "Horizontal (mm)": "Horizontal (mm)",
    "Vertical (mm)": "Vertical (mm)",
    "Reset": "Zerar",
    "Body Composition Sheet": "Folha de Composição Corporal",
    "Body Water Sheet": "Folha de Água Corporal",
    "Children's Sheet": "Folha Infantil (Criança)",
    "Body Composition History": "Histórico de Composição Corporal",
    "Date / Time": "Data / Hora",
    "Skeletal Muscle\nMass": "Massa Muscular\nEsquelética",
    "Percent\nBody Fat": "Porcentual\nde Gordura",
    "ECW/TBW": "Taxa de AEC",
    "Period": "Período",
    "Visceral Fat Level": "Nível de Gordura Visceral",
    "Results interpretation": "Interpretação de resultados",
    "Body Composition Analysis": "Análise da Composição Corporal",
    "Body weight is the sum of Total Body Water,": "O peso do corpo é a soma de Água Corporal Total,",
    "protein, minerals, and body fat mass.": "proteínas, sais minerais e massa de gordura.",
    "Keep a balanced body composition to": "Mantenha uma composição corporal equilibrada para",
    "stay healthy.": "permanecer saudável.",
    "Muscle-Fat Analysis": "Análise Músculo-Gordura",
    "Compare the bar lengths of skeletal muscle": "Compare os comprimentos das barras de massa muscular",
    "mass and body fat mass. The longer the skeletal": "esquelética e massa de gordura. Quanto maior a barra",
    "muscle bar is versus the body fat": "muscular em relação à barra de gordura",
    "bar, the stronger the body is.": "corporal, mais forte o corpo é.",
    "Obesity Analysis": "Análise de Obesidade",
    "BMI is an index used to determine": "O IMC é um índice usado para determinar",
    "obesity, using height and weight.": "a obesidade, pela altura e peso.",
    "PBF is the percent of body fat relative": "O PGC é o percentual de gordura corporal em relação",
    "to body weight.": "ao peso corporal.",
    "Segmental Lean Analysis": "Análise da Massa Magra Segmentar",
    "Assess whether muscle is distributed": "Avalia se o músculo está distribuído",
    "properly across all body parts.": "de forma adequada em todas as partes do corpo.",
    "Compares muscle mass to the ideal weight.": "Compara a massa muscular ao peso ideal.",
    "Segmental Fat Analysis": "Análise de Gordura Segmentar",
    "Assess whether fat is distributed": "Avalia se a gordura está distribuída",
    "Compares fat mass to the ideal weight.": "Compara a massa de gordura ao peso ideal.",
    "Results Interpretation QR Code": "Código QR da Interpretação de Resultados",
    "Scan the QR code to": "Digitalizar o código QR para",
    "see the interpretation of the": "ver a interpretação dos",
    "results in more detail.": "resultados com mais detalhes.",
    "Impedance": "Impedância",
    "Waist-Hip Ratio": "Relação Cintura-Quadril",
    "Level": "Nível",
    "Below": "Abaixo",
    "Above": "Acima",
    "Calories burned by exercise": "Perdas de calorias do exercício",
    "Golf": "Golfe",
    "Walking": "Caminhada",
    "Badminton": "Badminton",
    "Tennis": "Tênis",
    "Boxing": "Boxe",
    "Climbing": "Escalada",
    "Aerobics": "Aeróbica",
    "Soccer": "Futebol",
    "Kendo": "Esgrima japonesa",
    "Squash": "Squash",
    "Gateball": "Gate-ball",
    "Yoga": "Ioga",
    "Table tennis": "Tênis de mesa",
    "Cycling": "Ciclismo",
    "Basketball": "Basquetebol",
    "Jump rope": "Pular corda",
    "Jogging": "Jogging",
    "Swimming": "Natação",
    "Racquetball": "Raquetebol",
    "Taekwondo": "Taekwondo",
    "∗Based on your current weight": "∗Com base em seu peso atual",
    "∗Based on 30 minutes duration": "∗Com base em 30 minutos de duração",
    "QR Code": "Código QR",
    "Body Type": "Tipo de Corpo",
    "Athletic": "Atlético",
    "Muscular\nform": "Forma\nmuscular",
    "Obese": "Obesidade",
    "Muscular": "Musculoso",
    "Average": "Média",
    "Slightly\nObese": "Ligeiramente\nObeso",
    "Lean\nmuscular": "Magro\nmuscular",
    "Lean": "Magro",
    "Sarcopenic\nObesity": "Obesidade\nSarcopênica",
    "Very\nlean": "Muito\nmagro",
    "Slightly lean": "Um pouco magro",
    "Segmental Circumference": "Circunferência Segmentar",
    "Neck": "Pescoço",
    "Chest": "Peito",
    "Abdomen": "Abdômen",
    "Hip": "Quadril",
    "Right Thigh": "Coxa Direita",
    "Left Thigh": "Coxa Esquerda",
    "Additional data": "Dados adicionais",
    "Basal Metabolic Rate": "Taxa Metabólica Basal",
    "Recommended calorie intake": "Ingestão calórica recomendada",

    // ==== Settings Data/InBody (alertas e nuvem) 14/08/2026 ====
    "Export complete": "Exportação concluída",
    "CSV spreadsheet (opens in Excel) saved to:": "Planilha CSV (abre no Excel) salva em:",
    "Export failed": "Exportação falhou",
    "Could not write": "Não consegui gravar",
    "Backup complete": "Backup concluído",
    "Full database copy saved to:": "Cópia completa do banco salva em:",
    "Backup failed": "Backup falhou",
    "No folder chosen": "Nenhuma pasta escolhida",
    "Use this folder": "Usar esta pasta",
    "Choose the folder (iCloud Drive, Google Drive, OneDrive, or other) where the automatic backup will be saved.": "Escolha a pasta (iCloud Drive, Google Drive, OneDrive ou outra) onde o backup automático será gravado.",
    "Backup location changed": "Local do backup alterado",
    "The automatic backup will now be saved to:": "O backup automático passará a ser gravado em:",
    "Close and reopen this screen to see the new path in the field.": "Feche e reabra esta tela para ver o novo caminho no campo.",
    "Invalid backup": "Backup inválido",
    "No .mdb file found inside": "Não achei um arquivo .mdb dentro de",
    "Restore complete": "Restauração concluída",
    "The data was MERGED with the current data; nothing was deleted.": "Os dados foram MESCLADOS aos atuais; nada foi apagado.",
    "Template saved": "Modelo salvo",
    "Fill it in Excel and import with the button below.": "Preencha no Excel e importe pelo botão abaixo.",
    "Could not save": "Não consegui salvar",
    "Group import": "Importação de grupo",
    "Choose the folder (e.g. USB drive) to save the copy.": "Escolha a pasta (ex.: pen drive) para salvar a cópia.",
    "Copy saved": "Cópia salva",
    "Failed": "Falhou",
    "Nothing to delete": "Nada a apagar",
    "There are no temporary measurements.": "Não há medições temporárias.",
    "temporary measurement(s)?": "medição(ões) temporária(s)?",
    "This removes only temporary (unsaved) ones. Saved exams are not affected.": "Isso remove só as temporárias (não salvas). Exames salvos não são afetados.",
    "Done": "Pronto",
    "temporary one(s) removed.": "temporária(s) removida(s).",
    "* Restore MERGES the backup data with the current data. Nothing is deleted.": "* A restauração MESCLA os dados do backup com os atuais. Nada é apagado.",
    "1) Click [Data Restoration].  2) Choose the .mdb file or a .zip from the scale backup folder.": "1) Clique em [Data Restoration].  2) Escolha o arquivo .mdb ou um .zip da pasta de backup da balança.",
    "Choose the destination folder.": "Escolha a pasta de destino.",
    "Exported:": "Exportado:",
    "Export failed.": "Falha ao exportar.",
    "Restore default?": "Restaurar padrão?",
    "Resets output/print options to factory default. Does not touch patients.": "Volta as opções de saída/impressão ao padrão de fábrica. Não mexe em pacientes.",
    "Restore": "Restaurar",
    "Model detected on connection: 770.": "Modelo detectado na conexão: 770.",
    "Cloud login (use the cloud backup above)": "Login na nuvem (use o backup na nuvem acima)",
    "Cloud backup": "Backup na nuvem",
    "Link your cloud folder (iCloud Drive, Google Drive, or OneDrive). The app writes the copy there and the cloud syncs it on its own.": "Vincule a pasta da sua nuvem (iCloud Drive, Google Drive ou OneDrive). O app grava a cópia lá e a nuvem sincroniza sozinha.",
    "(no folder linked)": "(nenhuma pasta vinculada)",
    "Change folder": "Trocar pasta",
    "Back up now": "Backup agora",
    "Automatic backup on app launch": "Backup automático ao abrir o app",
    "Cloud backup saved:": "Backup salvo na nuvem:",
    "Choose your cloud folder (iCloud Drive, Google Drive, or OneDrive).": "Escolha a pasta da sua nuvem (iCloud Drive, Google Drive ou OneDrive).",
    "Link": "Vincular",
    "Folder linked. Click Back up now whenever you want.": "Pasta vinculada. Clique em Backup agora quando quiser.",
    "Backup failed.": "Falha no backup.",

    // ==== Health Report (métricas + interpretações) 14/08/2026 ====
    "Weight is the sum of the four body composition components: Total Body Water, Protein, Minerals, and Body Fat Mass.": "O peso é a soma dos quatro componentes da composição corporal: Água Corporal Total, Proteína, Minerais e Massa de Gordura.",
    "Skeletal muscle mass is the muscle attached to bones and moved voluntarily. It increases with exercise.": "A massa muscular esquelética é o músculo preso aos ossos e movido de forma voluntária. Aumenta com o exercício.",
    "Body fat mass is the sum of subcutaneous fat, visceral fat, and fat around the muscles.": "A massa de gordura é a soma da gordura subcutânea, da gordura visceral e da gordura ao redor dos músculos.",
    "Percent body fat is the ratio of body fat mass to body weight.": "O percentual de gordura é a razão entre a massa de gordura e o peso corporal.",
    "Total Body Water": "Água Corporal Total",
    "Total Body Water is the sum of the water inside and outside the cells.": "Água Corporal Total é a soma da água dentro e fora das células.",
    "Intracellular Water": "Água Intracelular",
    "Intracellular Water is the water contained inside the body cells.": "Água Intracelular é a água contida dentro das células do corpo.",
    "Extracellular Water": "Água Extracelular",
    "Extracellular Water is the water outside the cells (blood and interstitial fluid).": "Água Extracelular é a água fora das células (sangue e líquido intersticial).",
    "ECW/TBW Ratio": "Relação AEC/ACT",
    "Ratio of Extracellular Water to Total Body Water. A marker of fluid balance and inflammation.": "Razão entre a Água Extracelular e a Água Corporal Total. Marcador de equilíbrio hídrico e inflamação.",
    "Change in body weight across exams.": "Evolução do peso corporal ao longo dos exames.",
    "Change in skeletal muscle mass.": "Evolução da massa muscular esquelética.",
    "Change in body fat mass.": "Evolução da massa de gordura.",
    "Change in percent body fat.": "Evolução do percentual de gordura corporal.",
    "Body Mass Index": "Índice de Massa Corporal",
    "Change in BMI (weight divided by height squared).": "Evolução do IMC (peso dividido pela altura ao quadrado).",
    "Visceral Fat": "Gordura Visceral",
    "Change in visceral fat area.": "Evolução da área de gordura visceral.",
    "Hide interpretation": "Ocultar interpretação",
    "Show interpretation": "Mostrar interpretação",

    // ==== Sweep de tradução 14/08/2026 (telas ligadas ao T + folha em inglês) ====
    "Email": "E-mail",
    "Export PDF": "Exportar PDF",
    "Date": "Data",
    "Connect": "Conectar",
    "Refresh": "Atualizar",
    "via": "via",
    "yrs": "anos",
    "exam": "exame",
    "exams": "exames",
    "measured on": "medido em",
    "BMI": "IMC",
    "Metabolism": "Metabolismo",
    "Waist-hip": "Cintura-quadril",
    "Low": "Baixa",
    "Import backup": "Importar backup",
    "Search patient": "Buscar paciente",
    "Connect scale": "Conectar balança",
    "Scale connected": "Balança conectada",
    "Developed by": "Desenvolvido por",
    "Recipient email": "E-mail do destinatário",
    "Last Login:": "Último acesso:",
    "Category:": "Categoria:",
    "Scale connection": "Conexão com a balança",
    "Searching for the scale…": "Procurando a balança…",
    "Network — WiFi / LAN": "Rede — WiFi / LAN",
    "Serial port (dongle/cable)": "Porta serial (dongle/cabo)",
    "No serial port. Plug in the dongle/cable and click Refresh.": "Nenhuma porta serial. Ligue o dongle/cabo e clique em Atualizar.",
    "Serial cable (RS-232)": "Cabo serial (RS-232)",
    "Search automatically (tries all methods)": "Procurar automaticamente (tenta todos os meios)",
    "No scale connected.": "Nenhuma balança conectada.",
    "intra + extracellular": "intra + extracelular",
    "adipose tissue": "tecido adiposo",
    "% of weight": "% do peso",
    "basal kcal": "kcal basal",
    "1. In \"Results sheets\", click the cells to choose what to print.": "1. Em \"Folhas de resultado\", clique nas células para escolher o que imprimir.",
    "* By default, each patient's most recent exam is already checked.": "* Por padrão, já vem marcado o exame mais recente de cada paciente.",
    "Sheet not built yet": "Folha ainda não construída",
    "is not printed by the app yet.": "ainda não é impressa pelo app.",
    "Select a patient with an exam.": "Selecione um paciente com exame.",
    "I opened your Mac email with the exam attached. Just click Send.": "Abri o e-mail do seu Mac com o exame anexado. É só clicar em Enviar.",
    "Attached is the body composition exam result.": "Segue em anexo o resultado do exame de composição corporal.",
    "Version 1.0.0": "Versão 1.0.0",
    "· First edition for macOS": "· Primeira edição para macOS",
    "Body composition app for macOS: live exam, result sheets, printing, email, backup and restore, cloud backup, and scale connection (WiFi, Bluetooth, USB, and serial).": "App de composição corporal para macOS: exame ao vivo, folhas de resultado, impressão, e-mail, backup e restauração, backup na nuvem e conexão com a balança (WiFi, Bluetooth, USB e serial).",
    "Version 1.0.0 · First edition for macOS": "Versão 1.0.0 · Primeira edição para macOS",
    "Concept and development": "Ideia e desenvolvimento",
    "Non-profit app.": "App sem fins lucrativos.",
    "No exam to preview": "Sem exame para pré-visualizar",
    "Select a patient with an exam in the main list.": "Selecione um paciente com exame na lista principal.",

    // Sweep de tradução 11/08/2026 (strings que ainda saíam em inglês)
    "Height (cm)": "Altura (cm)",
    "End": "Fim",
    "• Check that the InBody is on the same network and powered on.\n• Confirm the InBody model and interface under Setup.\n• Always connect a Blood Pressure Monitor from InBody.":
        "• Confira que a InBody está na mesma rede e ligada.\n• Confirme o modelo e a interface da InBody no Setup.\n• Conecte sempre um monitor de pressão da InBody.",
    "2. Edit cells directly, like an Excel spreadsheet.":
        "2. Edite as células direto, como numa planilha do Excel.",
    "2024-10-15 Update History  ·  Program Version: 5.0.0.1(005A)":
        "2024-10-15 Histórico de atualização  ·  Versão do programa: 5.0.0.1(005A)",
    "1. Stabilizing the program  ·  Corrected minor bugs.":
        "1. Estabilização do programa  ·  Pequenas correções.",
    // Folhas / relatórios (nomes que aparecem no Print e nos Health Reports)
    "Blood Pressure": "Pressão Arterial",
    "Blood Glucose": "Glicemia",
    "Blood Pressure Results Sheet": "Folha de Pressão Arterial",
    "Blood Glucose Results Sheet": "Folha de Glicemia",
    "Blood Pressure Results\nSheet": "Folha de\nPressão Arterial",
    "Blood Glucose Results\nSheet": "Folha de\nGlicemia",
    "Blood Pressure\nResults Sheet": "Folha de\nPressão Arterial",
    "Blood Glucose\nResults Sheet": "Folha de\nGlicemia",
    "Body Composition\nHistory Result Sheet": "Folha de Histórico\nda Composição Corporal",
    // Guia de reinstalação (C-03) e importação (C-08)
    "1. Prepare a USB Thumb Drive (≥500MB).": "1. Prepare um pen drive (≥500MB).",
    "2. Click [Data Storage] to save data to the LookinBody120_Backup folder on the USB.":
        "2. Clique em [Data Storage] para salvar os dados na pasta LookinBody120_Backup do pen drive.",
    "3. Copy the LookinBody120_download.url file to the USB.":
        "3. Copie o arquivo LookinBody120_download.url para o pen drive.",
    "4. Plug the Hardlock Key into the new computer.":
        "4. Conecte a chave Hardlock no computador novo.",
    "5. Run the downloaded installer.": "5. Rode o instalador baixado.",
    "6. Restore the data from the USB backup folder.":
        "6. Restaure os dados da pasta de backup do pen drive.",
    "7. Confirm the member data and settings.":
        "7. Confira os dados dos pacientes e as configurações.",
    "2) Open the file.  3) Refer to instructions.  4) Save and close.":
        "2) Abra o arquivo.  3) Siga as instruções.  4) Salve e feche.",
    "1) Click [Data Importation] below.  2) Select the USB used to export data from the InBody. Open the 'inbody' folder, then select the 'lookinbody' folder.":
        "1) Clique em [Data Importation] abaixo.  2) Escolha o pen drive usado para exportar da InBody. Abra a pasta 'inbody' e depois a pasta 'lookinbody'.",
    "* If the InBody Test was taken without age or gender, results cannot be saved — only member information will be saved.":
        "* Se o exame foi feito sem idade ou sexo, os resultados não podem ser salvos — só os dados do paciente serão salvos.",

    // Tela principal / lista
    "Search by Name or ID": "Buscar por nome ou ID",
    "Register New": "Cadastrar novo",
    "Member Info.": "Dados do paciente",
    "Member(s)": "Paciente(s)",
    "Name": "Nome",
    "ID": "ID",
    "Age": "Idade",
    "Gender": "Sexo",
    "Weight": "Peso",
    "Body Fat": "Gordura corporal",
    "Skeletal Muscle Mass": "Massa muscular esquelética",
    "Test Date / Time": "Data / hora do exame",
    "Recent": "Recente",
    "Recent Results : ": "Exames recentes: ",
    "First, select a member.": "Selecione um paciente.",
    "'Select Test' or 'Manage Results' on top after selecting":
        "Depois de selecionar, use 'Exame' ou 'Resultados' no topo",
    "Setup": "Configurações",
    "Shortcut:": "Atalho:",
    "Troubleshooting": "Ajuda",
    "Connection help": "Ajuda de conexão",
    "User's Guide": "Guia de uso",
    "Health Report": "Relatório de saúde",
    "Health Report : InBody": "Relatório de saúde",
    "InBody": "InBody",
    "Start": "Iniciar",
    "Save": "Salvar",
    "Delete": "Excluir",
    "Confirm": "Confirmar",
    "Preview": "Visualizar",
    "Send": "Enviar",
    "Compose": "Escrever",
    "Attach": "Anexar",
    "Attachment(s)": "Anexo(s)",
    "Subject": "Assunto",
    "Add ▾": "Adicionar ▾",
    "Optional": "Opcional",
    "Required": "Obrigatório",
    "Zip Code": "CEP",
    "Day": "Dia",
    "Mo.": "Mês",
    "Yr.": "Ano",
    "cm": "cm",

    // Cadastro
    "* Auto-assign ID?": "* Gerar ID automaticamente?",
    "* Lowercase alphabets and numbers, -, _ only (1-14 characters)":
        "* Só letras minúsculas, números, - e _ (1 a 14 caracteres)",
    "* Medical history(s) and group(s) can be modified in Setup.":
        "* Histórico médico e grupos podem ser alterados nas Configurações.",
    "For children under 18, input date of birth to determine the exact age.":
        "Para menores de 18 anos, informe a data de nascimento para a idade exata.",
    "Delete Member": "Excluir paciente",
    "Deleting a member will permanently erase his/her results. If deleted, results cannot be restored.":
        "Excluir o paciente apaga os exames dele de vez. Não dá para desfazer.",
    "All results will be permanently deleted and cannot be restored.":
        "Todos os exames serão apagados de vez e não podem ser recuperados.",

    // Exame
    "InBody Test Completed": "Exame concluído",
    "InBody Test completed.": "Exame concluído.",
    "Save InBody result into My PC": "Salvar o resultado no computador",
    "Blood Pressure Test Completed": "Aferição de pressão concluída",
    "Blood pressure test completed.": "Aferição de pressão concluída.",
    "Save Blood pressure result into My PC": "Salvar a pressão no computador",
    "Blood Pressure Monitor connected": "Medidor de pressão conectado",
    "* Click [InBody] under Health Report to view detailed results.":
        "* Clique em [InBody] no Relatório de saúde para ver o resultado completo.",
    "* Click [Blood Pressure] under Health Report to view detailed results.":
        "* Clique em [Pressão] no Relatório de saúde para ver o resultado completo.",
    "* Click [Print] on top to print Results Sheet(s).":
        "* Clique em [Imprimir] no topo para imprimir as folhas.",

    // Impressão
    "Results Sheet": "Folha de resultado",
    "Result Sheet Category": "Categoria da folha",
    "Select Result Sheet": "Escolha a folha",
    "Select Result Sheet(s)": "Escolha as folhas",
    "InBody Result Sheet": "Folha de resultado",
    "Results Interpretation: ": "Interpretação do resultado: ",

    // Login / conta
    "Log in": "Entrar",
    "If password is forgotten, contact Customer Service.":
        "Esqueceu a senha? Fale com o suporte.",
    "Initial ID and Password is inbody/0000. Please change your ID and Password":
        "Usuário e senha iniciais: inbody/0000. Troque depois de entrar.",
    "Initial ID and Password is inbody/0000. If you wish to change your password please go to Setup > Account Management and change your ID and Password":
        "Usuário e senha iniciais: inbody/0000. Para trocar, vá em Configurações > Conta.",
    "Password: at least 8 characters incl. upper/lowercase letters and special characters.":
        "Senha: ao menos 8 caracteres, com maiúscula, minúscula e caractere especial.",
    "A verification number will be sent to the email address below.":
        "Um código de verificação será enviado para o e-mail abaixo.",
    "Verification Number": "Código de verificação",
    "Verification number sent.": "Código de verificação enviado.",
    "Response Code": "Código de resposta",

    // Rótulos do cadastro
    "Height": "Altura",
    "Date of Birth": "Data de nascimento",
    "Mobile No.": "Celular",
    "Tel. No.": "Telefone",
    "Address": "Endereço",
    "E-mail": "E-mail",
    "Medical history": "Histórico médico",
    "Group": "Grupo",
    "Male": "Masculino",
    "Female": "Feminino",
    "Yes": "Sim",
    "No": "Não",
    "Show": "Mostrar",
    "Hide": "Ocultar",
    "Register": "Cadastrar",
    "Print Form": "Imprimir ficha",
    "Verification": "Verificar",
    "None": "Nenhum",
    "Edit": "Editar",
    "Cancel": "Cancelar",
    "Close": "Fechar",
    "Print": "Imprimir",
    "Start Print": "Imprimir",
    "E-mail ": "E-mail ",
    "Import": "Importar",
    "Export": "Exportar",
    "Logout": "Sair",

    // Setup
    "Select country.": "Escolha o país.",
    "Select language.": "Escolha o idioma.",
    "Select unit.": "Escolha a unidade.",
    "Select date format.": "Escolha o formato da data.",
    "Select a printer.": "Escolha a impressora.",
    "Select options below.": "Escolha as opções abaixo.",
    "General Settings": "Configurações gerais",
    "InBody Test Settings": "Configurações do exame",
    "OK": "OK",

    // ===== Telas de Configuração (Setup A/B/C/D) e listas =====
    "All Members": "Todos os pacientes",
    "person(s)": "pessoa(s)",
    // Seletores de busca e ordenação (Store.ModoBusca/Ordenacao)
    "Name or ID": "Nome ou ID",
    "Name Ascending": "Nome (A→Z)",
    "Name Descending": "Nome (Z→A)",
    "ID Ascending": "ID (crescente)",
    "ID Descending": "ID (decrescente)",
    // Status da balança
    "Disconnected": "Desconectado",
    ", Blood Pressure Monitor": ", Medidor de pressão",
    // Program Info (A-10) + bloqueio (A-08)
    "Balance": "Balança",
    "Computer name": "Nome do computador",
    "Computer IP address": "IP do computador",
    "Screen locked": "Tela bloqueada",
    "Unlock": "Desbloquear",
    "Wrong password.": "Senha incorreta.",
    // Animação do exame
    "Measuring…": "Medindo…",
    "Step barefoot on the InBody and stay still.": "Suba descalço na balança e fique parado.",
    "Recent Results :": "Exames recentes:",
    "Test Date/Time": "Data/hora do exame",
    "Select": "Selecionar",
    "DOB or Age": "Nasc. ou idade",
    "Height\n(cm)": "Altura\n(cm)",
    "Member\nInfo.": "Dados do\nPaciente",
    "InBody\nTest": "Exame\nInBody",
    "Blood\nPressure": "Pressão\nArterial",
    "Blood\nGlucose": "Glicemia",
    "Blood Pressure\nTest": "Teste de\nPressão",
    "Hide Interpretation": "Ocultar interpretação",
    "Two-factor authentication": "Autenticação de dois fatores",
    "Forgot Password": "Esqueci a senha",
    "Change": "Alterar",
    "Permanently delete?": "Excluir permanentemente?",
    "Add Member": "Adicionar paciente",
    "Add Blood Pressure": "Adicionar pressão",
    "Add Blood Glucose": "Adicionar glicemia",
    // A-01/A-08/A-09/A-10/A-11
    "Secure Connection": "Conexão segura",
    "Set an account to send e-mails.": "Defina uma conta para enviar e-mails.",
    "Setup auto-lock to prevent unauthorized usage.": "Configure o bloqueio automático para impedir uso não autorizado.",
    "Min": "min",
    "Input password.": "Digite a senha.",
    "Input password again.": "Digite a senha novamente.",
    "Save the customer service provider's information in case of inquiries.": "Guarde os dados do suporte para eventuais dúvidas.",
    "Program Information": "Informações do programa",
    "Computer Information": "Informações do computador",
    "Update History": "Histórico de atualizações",
    "GDPR Option setup": "Configuração de opções LGPD",
    // B — InBody Test Settings
    "Cloud service lets clients check and manage their results from their own smartphone.": "O serviço de nuvem permite ao paciente ver e gerenciar os resultados no próprio celular.",
    "The contact information for Customer Service is shown below.": "Os contatos do suporte aparecem abaixo.",
    "LookinBody Website Account Login": "Login da conta no site o app",
    "You are not logged in.": "Você não está conectado.",
    "Message settings (SMS/MMS)": "Configurações de mensagem (SMS/MMS)",
    "Select outputs/interpretations to print on the right side of the InBody Results Sheet, or shown as Body Composition History graphs on the Health Report.": "Selecione os itens/interpretações impressos no lado direito da folha, ou exibidos como gráficos de histórico no Relatório de Saúde.",
    "Free Space": "Espaço livre",
    "Your personal information is printed on the upper part of the result sheet. Print name and date of birth as well?": "Seus dados pessoais são impressos na parte superior da folha. Imprimir também nome e data de nascimento?",
    "Set normal ranges below. The graph will be drawn accordingly.": "Defina as faixas normais abaixo. O gráfico será desenhado conforme elas.",
    "Normal Range": "Faixa normal",
    "Ideal Value": "Valor ideal",
    "▲ Ideal Value": "▲ Valor ideal",
    "Select the standard child growth curve type.": "Selecione o tipo de curva de crescimento infantil.",
    "• BMI (kg/㎡)": "• IMC (kg/㎡)",
    "• Percent Body Fat (%)": "• Percentual de gordura (%)",
    "• Waist-Hip Ratio": "• Relação cintura-quadril",
    "• Standard Child Growth Curve": "• Curva de crescimento infantil",
    "To export data to EMR you must first specify a destination folder.": "Para exportar ao prontuário, defina antes uma pasta de destino.",
    "LookinBody  →  Folder  →  EMR": "o app  →  Pasta  →  Prontuário",
    "Auto Export": "Exportação automática",
    "Convert results automatically to an image file after each InBody Test?": "Converter os resultados automaticamente em imagem após cada exame?",
    "Image Destination Folder": "Pasta de destino da imagem",
    "Convert results automatically to CSV files after each InBody Test?": "Converter os resultados automaticamente em CSV após cada exame?",
    "CSV Destination Folder": "Pasta de destino CSV",
    "Order Destination Folder": "Pasta de destino do pedido",
    "Manual Export": "Exportação manual",
    "InBody Test Date": "Data do exame",
    // C — Data Management
    "Export data to edit and save as Excel.": "Exporte os dados para editar e salvar em Excel.",
    "Search by InBody Test Date": "Buscar por data do exame",
    "Click the button below to export data.": "Clique no botão abaixo para exportar.",
    "Register a group of members by importing a batched group from the provided LookinBody Excel file.": "Cadastre um grupo de pacientes importando o Excel fornecido pelo o app.",
    "To reinstall LookinBody, the install files and any saved data must be on a USB Thumb Drive. The provided Hardlock Key must also be plugged into the computer.": "Para reinstalar o o app, os arquivos de instalação e os dados salvos precisam estar em um pen drive USB. A chave Hardlock fornecida também precisa estar conectada.",
    "Data Backup will save all member information, results, and user settings.": "O backup salva todos os pacientes, resultados e configurações.",
    "Click the button below to backup data.": "Clique no botão abaixo para fazer o backup.",
    "Auto backup location": "Local do backup automático",
    "Auto backup period setting": "Período do backup automático",
    "Last Backup: -": "Último backup: -",
    "Restore data from a previous LookinBody backup file.": "Restaure os dados de um backup anterior do app.",
    "* Data restoration will delete all of your current data.": "* A restauração apaga todos os dados atuais.",
    "Temporarily saved test results are shown below.": "Os resultados salvos temporariamente aparecem abaixo.",
    "Import Data from past versions of LookinBody to LookinBody120.": "Importe dados de versões anteriores do app para o o app120.",
    "Import data saved from the InBody by using the USB Thumb Drive.": "Importe dados salvos da balança por pen drive USB.",
    // D — Integração
    "Data integration method": "Método de integração de dados",
    "DICOM Encoding": "Codificação DICOM",
    "Image laterality": "Lateralidade da imagem",
    "FTP Type": "Tipo de FTP",
    // Pressão / glicose
    "Systolic": "Sistólica",
    "Systolic (mmHg)": "Sistólica (mmHg)",
    "Systolic/Diastolic Blood Pressure ": "Pressão sistólica/diastólica ",
    "mmHg  Diastolic": "mmHg  Diastólica",
    "No readings yet. Blood glucose is entered via Edit.": "Sem leituras ainda. A glicemia é inserida em Editar.",
    "Only the highlighted member's blood pressure test will begin.\n* Click another member to highlight.": "Só o exame de pressão do paciente destacado vai começar.\n* Clique em outro paciente para destacá-lo.",

    // ===== Setup detalhado (A/B/C/D) lote 2 =====
    "Select Member": "Selecionar paciente",
    "Select Test": "Selecionar exame",
    "Manage Results": "Gerenciar resultados",
    "Search": "Buscar",
    "List All": "Listar todos",
    "Add": "Adicionar",
    "Total": "Total",
    "Login": "Entrar",
    "InBody Test": "Exame",
    "Example": "Exemplo",
    "Printing Alignment": "Alinhamento de impressão",
    "Set Password for Setup": "Definir senha do Setup",
    "Set Master Password": "Definir senha mestra",
    "Prevent unauthorized access to the Setup.": "Impede acesso não autorizado ao Setup.",
    "Click the button below to set a password.": "Clique no botão abaixo para definir uma senha.",
    "Year.Month.Day.": "Ano.Mês.Dia.",
    "Month.Day.Year.": "Mês.Dia.Ano.",
    "Day.Month.Year.": "Dia.Mês.Ano.",
    "1. Select Results Sheet type to print.": "1. Selecione o tipo de folha a imprimir.",
    "Category · Results Sheet · Example / Setup · Model": "Categoria · Folha · Exemplo / Setup · Modelo",
    "2. Select the paper type.": "2. Selecione o tipo de papel.",
    "Blank A4 Paper": "Papel A4 em branco",
    "InBody Paper": "Papel pré-impresso",
    "* To adjust print alignment, click [Printing Alignment].": "* Para ajustar o alinhamento, clique em [Alinhamento de impressão].",
    "3. Select number of copies to print.": "3. Selecione o número de cópias.",
    "1 copy": "1 cópia",
    "2 copies": "2 cópias",
    "4. Print Results Sheets automatically after each InBody Test.": "4. Imprimir as folhas automaticamente após cada exame.",
    "Print automatically": "Imprimir automaticamente",
    "Do not print automatically": "Não imprimir automaticamente",
    "5. Set language for Results Sheets.": "5. Idioma das folhas de resultado.",
    "Shows research data.": "Mostra dados de pesquisa.",
    "Research Result Sheet": "Folha de pesquisa",
    "Configuração do logo em texto": "Configuração do logo em texto",
    "Selecione a opção de logo.": "Selecione a opção de logo.",
    "1. Select account.": "1. Selecione a conta.",
    "InBody account": "Conta da balança",
    "User account": "Conta própria",
    "E-mail using your own account. Information below is required.": "E-mail pela sua conta. Os dados abaixo são necessários.",
    "2. Input the required information.": "2. Preencha os dados necessários.",
    "* This e-mail address will be shown to your members.": "* Este e-mail será exibido aos pacientes.",
    "* This user name will be shown to your members.": "* Este nome será exibido aos pacientes.",
    "Password": "Senha",
    "Port": "Porta",
    "Salvar e-mail": "Salvar e-mail",
    "Use": "Usar",
    "Do not use": "Não usar",
    "TLS 1.2": "TLS 1.2",
    "Select the type of results sheet to attach.": "Selecione o tipo de folha a anexar.",
    "Check items to edit or delete first. Editing/deleting also changes member information for other members concerned.": "Marque os itens para editar ou excluir. Editar/excluir também altera os dados de outros pacientes envolvidos.",
    "Setup auto-lock?": "Ativar bloqueio automático?",
    "Auto-Lock after.": "Bloquear após.",
    "Screen will auto-lock after a set time. Input password to unlock screen.": "A tela bloqueia após um tempo. Digite a senha para desbloquear.",
    "Set auto-lock password.": "Defina a senha do bloqueio.",
    "* When connected to the InBody, information will automatically save in LookinBody.": "* Ao conectar à balança, os dados são salvos automaticamente no app.",
    "GOGOGOGOGO": "GOGOGOGOGO",
    "Data Save": "Salvar dados",
    "Data Storage": "Armazenamento",
    "Logs": "Registros",
    "User Logs": "Registros do usuário",
    "Use data save agreement": "Usar termo de consentimento de dados",
    "Use user logs": "Registrar ações do usuário",
    "Select the InBody model.": "Selecione o modelo da balança.",
    "The InBody model can be changed.": "O modelo da balança pode ser alterado.",
    "Connect Stadiometer": "Conectar estadiômetro",
    "Restore InBody Default": "Restaurar padrão InBody",
    "Do you want to enable the Cloud Service?": "Deseja ativar o serviço de nuvem?",
    "Would you like to back up your data and settings automatically?": "Deseja fazer backup automático dos dados e configurações?",
    "1. Set up a Cloud Service.  2. After setup, log in to your LookinBody Web account.": "1. Configure o serviço de nuvem.  2. Depois, entre na sua conta o app Web.",
    "Configure the message content sent to the client's phone: preview, sender phone, promotional text and company name.": "Configure a mensagem enviada ao celular do paciente: prévia, telefone do remetente, texto promocional e nome da empresa.",
    "Output = a result of the InBody Test. Interpretation = an explanation of the output. Bracketed values [n] show required space.": "Item = um resultado do exame. Interpretação = a explicação do item. Valores entre [n] indicam o espaço necessário.",
    "* You can change the order by clicking the arrow. You can select only 4 outputs on the Evaluation Result Sheet.": "* Você pode mudar a ordem clicando na seta. Só 4 itens podem aparecer na folha de avaliação.",
    "With Values": "Com valores",
    "Without Values": "Sem valores",
    "* The normal ranges set will only be applied to adults. For children, a separate set is used and cannot be changed.": "* As faixas normais valem só para adultos. Para crianças usa-se um conjunto separado, que não pode ser alterado.",
    "* Cannot input values less than 23.0.": "* Não é possível inserir valores menores que 23,0.",
    "Option 1   Male 22 / Female 21.5": "Opção 1   Homem 22 / Mulher 21,5",
    "Option 2   Male 22 / Female 21": "Opção 2   Homem 22 / Mulher 21",
    "Option 3   18.5 ~": "Opção 3   18,5 ~",
    "Option": "Opção",
    "* Recommended by WHO.": "* Recomendado pela OMS.",
    "The Korean Pediatric Society 2007/2017 curve is also available depending on country.": "A curva da Sociedade Coreana de Pediatria 2007/2017 também está disponível conforme o país.",
    "Switzerland": "Suíça",
    "Convert to Image File": "Converter em imagem",
    "Convert to CSV File": "Converter em CSV",
    "1. Convert results in LookinBody to image/CSV and save to your destination folder.  2. Results in the folder are available for use in EMR.": "1. Converta os resultados em imagem/CSV e salve na pasta de destino.  2. Os arquivos na pasta ficam disponíveis para o prontuário.",
    "* Convert remaining results to image files?": "* Converter os resultados restantes em imagem?",
    "* Convert remaining results to CSV files?": "* Converter os resultados restantes em CSV?",
    "Export file path": "Caminho de exportação",
    "Export Data as Excel": "Exportar dados em Excel",
    "1. Input data in the provided LookinBody Excel file.": "1. Preencha os dados no Excel do app.",
    "2. Import the completed file.": "2. Importe o arquivo preenchido.",
    "Save LBGroupRegistration.xls on Desktop": "Salvar LBGroupRegistration.xls na Área de Trabalho",
    "Import LBGroupRegistration.xls": "Importar LBGroupRegistration.xls",
    "Remember to back up data when planning to re-format, transfer data, or remove/reinstall LookinBody.": "Lembre de fazer backup antes de formatar, transferir dados ou remover/reinstalar o o app.",
    "Data Backup": "Backup de dados",
    "Data Restoration": "Restauração de dados",
    "Data Importation": "Importação de dados",
    "* Auto backup will be made after this period since the last backup date. You can only backup data with the server computer.": "* O backup automático ocorre após esse período desde o último backup. Só é possível no computador servidor.",
    "* The restored data from LookinBody will be merged with your current data.": "* Os dados restaurados do app serão mesclados aos atuais.",
    "* The restored data will be merged with your current data.": "* Os dados restaurados serão mesclados aos atuais.",
    "Import Data from Previous LookinBody": "Importar dados de o app anterior",
    "Locate the folder with data, then click [OK]. Please use this function on the server computer.": "Localize a pasta com os dados e clique em [OK]. Use esta função no computador servidor.",
    "File extensions: .DAT / .INF / .CLG / .TRG": "Extensões: .DAT / .INF / .CLG / .TRG",
    "Import file path": "Caminho de importação",
    "Detailed integration methods are provided in a separate manual. LookinBody120 is a local PC program and does not provide a dedicated server.": "Os métodos de integração detalhados estão em manual separado. O o app120 é um programa local e não fornece servidor dedicado.",
    "If you forgot your password, please contact our Customer Service Center.": "Se esqueceu a senha, entre em contato com o suporte.",

    // ===== Menu do Setup =====
    "LookinBody Data Management": "Gerenciamento de dados",
    "Data Integration": "Integração de dados",
    "01. Country/Language/Units/Date Format/Password": "01. País/Idioma/Unidades/Formato de data/Senha",
    "02. Printer": "02. Impressora",
    "03. Results Sheet Types/Paper Types/Printing Options/Automatic Printing Options": "03. Tipos de folha/Papel/Impressão/Impressão automática",
    "04. Results Sheet Custom Logo": "04. Logo personalizado da folha",
    "05. E-mail Options": "05. Opções de e-mail",
    "06. Edit Member Information": "06. Editar dados do paciente",
    "07. N/A": "07. N/D",
    "06. N/A": "06. N/D",
    "08. Auto-Lock": "08. Bloqueio automático",
    "09. Customer Service Information": "09. Dados do suporte",
    "10. Program and Computer Information/Update History": "10. Informações do programa e do computador/Histórico",
    "11. Advanced Security": "11. Segurança avançada",
    "01. InBody Model": "01. Modelo da balança",
    "02. Cloud Service": "02. Serviço de nuvem",
    "03. Outputs/Interpretations for Results Sheet": "03. Itens/Interpretações da folha",
    "04. Reference Range": "04. Faixa de referência",
    "05. Export Data as CSV/Image Files": "05. Exportar dados em CSV/Imagem",
    "01. Export Data as Excel": "01. Exportar dados em Excel",
    "02. Import Group Registration Data as Excel": "02. Importar cadastro em grupo (Excel)",
    "03. Reinstallation Guide": "03. Guia de reinstalação",
    "04. Data Backup": "04. Backup de dados",
    "05. Data Restoration": "05. Restauração de dados",
    "06. Temporary Data": "06. Dados temporários",
    "07. Import Data from Previous LookinBody": "07. Importar dados de o app anterior",
    "08. Data Importation": "08. Importação de dados",
    "01. Order(Member) data integration": "01. Integração de dados de pedido (paciente)",
    "02. InBody data integration": "02. Integração de dados InBody",
    "03. InBody Results Sheet integration": "03. Integração da folha de resultado",
    "Results Sheet Types/Paper Types/Printing Options/Language for Results Sheet": "Tipos de folha/Papel/Opções de impressão/Idioma da folha",
    "GDPR Options": "Opções LGPD",

    // ===== Varredura final (relatórios, LGPD, glicemia, guias) =====
    "Connect InBody": "Conectar balança",
    "Connecting…": "Conectando…",
    "Connecting to the InBody…": "Conectando à balança…",
    "Profile sent": "Perfil enviado",
    "Step barefoot on the InBody to begin.": "Suba descalço na balança para começar.",
    "Measurement complete.": "Medição concluída.",
    "Connected": "Conectado",
    "Press [Start] on the blood pressure monitor to begin test.": "Aperte [Iniciar] no medidor de pressão para começar.",
    "Press [Start]…": "Aperte [Iniciar]…",
    "Start test": "Iniciar exame",
    "* Click 'Troubleshooting' on bottom for help.": "* Clique em 'Ajuda' embaixo para suporte.",
    "Failed to connect. The InBody Test cannot begin.\n* Click 'Troubleshooting' on bottom for help.": "Falha ao conectar. O exame não pode começar.\n* Clique em 'Ajuda' embaixo para suporte.",
    "Result:": "Resultado:",
    "Blood Pressure Test": "Teste de Pressão",
    "Shows InBody Test results with graphs.": "Mostra os resultados do exame com gráficos.",
    "Shows the balance and distribution of body water.": "Mostra o equilíbrio e a distribuição da água corporal.",
    "…results with graphs including Child Growth Curve.": "…resultados com gráficos, incluindo a curva de crescimento infantil.",
    "Explanation of the InBody Test results.": "Explicação dos resultados do exame.",
    "Tracks compositional change. Items selectable in Setup.": "Acompanha a mudança de composição. Itens selecionáveis nas Configurações.",
    "InBody Children's Result Sheet": "Folha de resultado infantil InBody",
    "InBody Result Interpretation": "Interpretação do resultado",
    "Body Water Result Sheet": "Folha de água corporal",
    "Body Composition History Result Sheet": "Folha de histórico de composição corporal",
    "Research Item": "Item de pesquisa",
    "Under": "Abaixo",
    "Normal": "Normal",
    "Over": "Acima",
    "Percent Body Fat": "Percentual de gordura",
    "Option 1  (18.5 ~ 25.0)": "Opção 1  (18,5 ~ 25,0)",
    "Option 2  (18.5 ~ 23.0)": "Opção 2  (18,5 ~ 23,0)",
    "(Ideal BMI value may shift the ideal weight value.)": "(O IMC ideal pode alterar o peso ideal.)",
    "(Ideal WHR value is the normal range median.)": "(A relação cintura-quadril ideal é a mediana da faixa normal.)",
    "(Ideal values of percent body fat are 15% for male and 23% for female.)": "(O percentual de gordura ideal é 15% para homens e 23% para mulheres.)",
    "(Min 23.0 / Max 29.0)": "(Mín 23,0 / Máx 29,0)",
    "(Min 16.0 / Max 50.0)": "(Mín 16,0 / Máx 50,0)",
    "(Min 5.0 / Max 14.0)": "(Mín 5,0 / Máx 14,0)",
    "(Min 5 / Max 22)": "(Mín 5 / Máx 22)",
    "(Min 24 / Max 50)": "(Mín 24 / Máx 50)",
    "(Min 0.50)": "(Mín 0,50)",
    "(Max 1.50)": "(Máx 1,50)",
    "Body Composition Analysis Output": "Análise da composição corporal",
    "Skeletal Muscle Mass Output": "Massa muscular esquelética",
    "Fat Free Mass Output": "Massa livre de gordura",
    "Basal Metabolic Rate Output": "Taxa metabólica basal",
    "Obesity Analysis Output": "Análise de obesidade",
    "Obesity Evaluation Output": "Avaliação de obesidade",
    "Body Type Output": "Tipo corporal",
    "InBody Score Output": "Pontuação InBody",
    "Weight Control Output": "Controle de peso",
    "Body Fat Mass": "Massa de gordura",
    "Bone Mineral Content Output": "Conteúdo mineral ósseo",
    "Extracellular Water Ratio Output": "Relação de água extracelular",
    "Segmental Lean Analysis Output": "Análise segmentar de massa magra",
    "Segmental Phase Angle Output": "Ângulo de fase segmentar",
    "Visceral Fat Area (Graph) Output": "Área de gordura visceral (gráfico)",
    "Visceral Fat Level Output": "Nível de gordura visceral",
    "Waist-Hip Ratio Output": "Relação cintura-quadril",
    "SMI Output (History)": "IMME (histórico)",
    "Whole Body Phase Angle (History)": "Ângulo de fase corporal (histórico)",
    "Account": "Conta",
    "Account Management": "Gerenciar conta",
    "Use Login": "Usar login",
    "Use user account": "Usar conta de usuário",
    "Use user authority": "Usar nível de acesso",
    "Use change password after 3 months": "Trocar senha a cada 3 meses",
    "Guardian verification": "Verificação de responsável",
    "Use guardian verification": "Usar verificação de responsável",
    "Use Privacy Policy Agreement": "Usar termo de privacidade",
    "Privacy information masking": "Mascaramento de dados",
    "Use privacy information masking lv.1": "Usar mascaramento nível 1",
    "Use privacy information masking lv.2": "Usar mascaramento nível 2",
    "Auto-assign ID": "Gerar ID automaticamente",
    "Privacy policy agreement": "Termo de privacidade",
    "Sensitive information offer agreement": "Termo de dados sensíveis",
    "Telephone No.": "Telefone",
    "Fax No.": "Fax",
    "Website": "Site",
    "Host": "Servidor",
    "User": "Usuário",
    "New ID": "Novo usuário",
    "New Password": "Nova senha",
    "Change Account": "Trocar conta",
    "Server Address": "Endereço do servidor",
    "Database Address": "Endereço do banco",
    "Database ID": "Usuário do banco",
    "Database Name": "Nome do banco",
    "Database Password": "Senha do banco",
    "DICOM export path": "Caminho de exportação DICOM",
    "Called AE title": "AE title chamado",
    "Calling AE title": "AE title chamador",
    "Sending Application": "Aplicação de envio",
    "Receiving Application": "Aplicação receptora",
    "Generate UID": "Gerar UID",
    "Recognition Code": "Código de reconhecimento",
    "Product Serial Number": "Número de série",
    "Registration Date": "Data de cadastro",
    "Accession number": "Número de acesso",
    "FTP Address": "Endereço FTP",
    "FTP Password": "Senha FTP",
    "FTP Port": "Porta FTP",
    "Every week (Default)": "Toda semana (padrão)",
    "Everyday": "Todo dia",
    "Every 3 days": "A cada 3 dias",
    "Every 5 days": "A cada 5 dias",
    "Every 15 days": "A cada 15 dias",
    "Every month": "Todo mês",
    "Every 2 months": "A cada 2 meses",
    "Every 3 months": "A cada 3 meses",
    "Diabetes": "Diabetes",
    "Dyslipidemia": "Dislipidemia",
    "Hyperlipidemia": "Hiperlipidemia",
    "Hypertension": "Hipertensão",
    "Osteoporosis": "Osteoporose",
    "PBF over": "Excesso de gordura",
    "Body composition": "Composição corporal",
    "Others": "Outros",
    "Trunk": "Tronco",
    "Right Arm": "Braço direito",
    "Left Arm": "Braço esquerdo",
    "Right Leg": "Perna direita",
    "Left Leg": "Perna esquerda",
    "Enter a new ID.": "Digite um novo ID.",
    "Enter a valid date of birth.": "Digite uma data de nascimento válida.",
    "Enter a valid height.": "Digite uma altura válida.",
    "Enter the member's name.": "Digite o nome do paciente.",
    "Enter your ID and Password.": "Digite seu usuário e senha.",
    "This ID already exists.": "Este ID já existe.",
    "Invalid ID or Password.": "Usuário ou senha inválidos.",
    "Select a gender.": "Selecione o sexo.",
    "Accept the agreements to register.": "Aceite os termos para cadastrar.",
    "ID: lowercase letters, numbers, - and _ only (1-14 characters).": "ID: só letras minúsculas, números, - e _ (1 a 14 caracteres).",
    "Password must be 8+ chars with upper/lowercase and a special character.": "A senha precisa de 8+ caracteres, com maiúscula, minúscula e um caractere especial.",
    "I agree to the Terms of Use, Privacy Policy, and Sensitive Information.": "Concordo com os Termos de Uso, a Política de Privacidade e os Dados Sensíveis.",
    "Accept Privacy Policy": "Aceitar a política de privacidade",
    "Accept terms and conditions": "Aceitar os termos e condições",
    "Start the InBody Test immediately after registration.": "Iniciar o exame logo após o cadastro.",
    "To save: 1. Input ID, height, date of birth (or age), and gender. 2. Check the data on the left, then click [Save].": "Para salvar: 1. Informe ID, altura, nascimento (ou idade) e sexo. 2. Confira os dados à esquerda e clique em [Salvar].",
    "Fasting": "Jejum",
    "2h After Meal": "2h após refeição",
    "Fasting Blood Glucose": "Glicemia de jejum",
    "Blood Glucose 2 Hours after a Meal": "Glicemia 2h após refeição",
    "Health Report : Blood Glucose": "Relatório de saúde: Glicemia",
    "Health Report : Blood Pressure": "Relatório de saúde: Pressão",
    "Show Interpretation": "Mostrar interpretação",
    "No readings yet. Readings come from the blood pressure monitor or from Edit.": "Sem leituras ainda. As leituras vêm do medidor de pressão ou de Editar.",
    "Prehypertension": "Pré-hipertensão",
    "Stage 1 Hypertension": "Hipertensão estágio 1",
    "Stage 2 Hypertension": "Hipertensão estágio 2",
    "Diastolic": "Diastólica",
    "Fasting Blood Glucose Level is the level of glucose in the blood after eight hours of fasting and is used as a screening test for diabetes.": "A glicemia de jejum é o nível de glicose no sangue após oito horas de jejum, usada como triagem de diabetes.",
    "Measured two hours after a meal to evaluate the body's ability to process glucose.": "Medida duas horas após a refeição para avaliar a capacidade do corpo de processar a glicose.",
    "Body Fat Mass is the sum of subcutaneous fat, visceral fat, and fat around muscles.": "A massa de gordura é a soma da gordura subcutânea, visceral e ao redor dos músculos.",
    "Percent Body Fat is the ratio of Body Fat Mass to body weight.": "O percentual de gordura é a razão entre a massa de gordura e o peso.",
    "Skeletal Muscle Mass is the muscle attached to bones and moved voluntarily. It increases with exercise.": "A massa muscular esquelética é o músculo preso aos ossos e movido voluntariamente. Aumenta com o exercício.",
    "Weight is the sum of the four components of body composition: Total Body Water, Protein, Minerals, and Body Fat Mass.": "O peso é a soma dos quatro componentes da composição corporal: água corporal total, proteína, minerais e massa de gordura.",
    "1. On the Results Sheet(s), select results sheets to print by clicking the cells.": "1. Nas folhas, selecione as que quer imprimir clicando nas células.",
    "2. On Data, select data to print and click the [Start Print] button to print.": "2. Em Dados, selecione o que imprimir e clique em [Imprimir].",
    "* Each member's most recent test results are selected as default.": "* O exame mais recente de cada paciente já vem selecionado.",
    "[How to Edit]": "[Como editar]",
    "* Delete: check a row, click Delete (permanent).": "* Excluir: marque a linha e clique em Excluir (permanente).",
    "* InBody results cannot be added here (only ID and date are editable).": "* Resultados InBody não podem ser adicionados aqui (só ID e data são editáveis).",
    "1. Use the Shortcut dropdown to switch column groups.": "1. Use o menu Atalho para trocar os grupos de colunas.",
    "Delete selected members?": "Excluir os pacientes selecionados?",
    "Delete selected records?": "Excluir os registros selecionados?",
    "1) Click [Data Restoration] below.  2) Select the folder that has the backup file.": "1) Clique em [Restauração de dados] abaixo.  2) Selecione a pasta com o arquivo de backup.",
    "2h After Meal ": "2h após refeição ",
    "Data": "Dados",
    "All": "Todos",
    "Fasting ": "Jejum ",

    // ===== Telas PT-nativas -> chave inglês =====
    "The full bar is the measured value. The tick marks the lower bound of the range.": "Barra cheia é o valor medido. O traço marca o limite inferior da faixa.",
    "Lean mass per segment, in kilos and % of expected.": "Massa magra por segmento, em quilos e em % do esperado.",
    "Extracellular / total water ratio.": "Relação água extracelular / total.",
    "Segmental lean mass analysis": "Análise segmentar de massa magra",
    "Change across measurements.": "Evolução ao longo das medições.",
    "Quick read of the exam.": "Leitura rápida do exame.",
    "Fat Free Mass": "Massa livre de gordura",
    "everything but fat": "tudo menos gordura",
    "Visceral fat": "Gordura visceral",
    "Water balance": "Balanço hídrico",
    "Muscle mass": "Massa muscular",
    "Body water": "Água corporal",
    "skeletal": "esquelética",
    "Lean mass": "Massa magra",
    "History": "Histórico",
    "Retention": "Retenção",
    "Indices": "Índices",
    "Fat": "Gordura",
    "Panel": "Painel",
    "Water": "Água",
    "LookinBody120 configuration screen. Options are saved with the button below.": "Tela de configuração do app120. As opções são salvas com o botão abaixo.",
    "The top-right corner of the sheet is available for a custom logo.": "O canto superior direito da folha fica disponível para logo personalizado.",
    "InBody account unavailable in this installation (feature not generated).": "Conta da balança indisponível nesta instalação (recurso não gerado).",
    "Sends via the account bundled with the program, no setup needed.": "Envia pela conta que acompanha o programa, sem configurar nada.",
    "* 'Use Login' will require login the next time the app opens.": "* 'Use Login' passa a exigir login na próxima abertura do app.",
    "The automatic print after the exam uses this printer.": "A impressão automática após o exame usa esta impressora.",
    "Auto-lock password already set (type to change).": "Senha do bloqueio já definida (digite para trocar).",
    "No printer installed on this Mac.": "Nenhuma impressora instalada neste Mac.",
    "Text logo configuration": "Configuração do logo em texto",
    "Missing host, user or password.": "Falta host, usuário ou senha.",
    "Select the logo option.": "Selecione a opção de logo.",
    "Saved (InBody account).": "Salvo (conta da balança).",
    "(image not loaded)": "(imagem não carregada)",
    "(system default)": "(padrão do sistema)",
    "Load image…": "Carregar imagem…",
    "No file": "Nenhum arquivo",
    "Save e-mail": "Salvar e-mail",
    "(no logo)": "(sem logo)",
    "Bold": "Negrito",
    "Saved.": "Salvo.",
    "No server configured: opened Mail with the attachment ready.": "Sem servidor configurado: abri o Mail com o anexo pronto.",
    "Could not generate the sheet PDF.": "Não consegui gerar a folha em PDF.",
    "Enter the recipient's e-mail.": "Informe o e-mail do destinatário.",
    "Recipient e-mail": "E-mail do destinatário",
    "Choose the registration spreadsheet (CSV). Need the template? Cancel and click Save template.": "Escolha a planilha (CSV) de cadastro. Precisa do modelo? Cancele e clique Salvar modelo.",
    "Import spreadsheet": "Importar planilha",
    "Model detected on connection: INBODY770.": "Modelo detectado na conexão: INBODY770.",
    "Connect balance": "Conectar balança",
    "Choose the balance's LookinBody.mdb file": "Escolha o arquivo o app.mdb da balança",
    "network": "rede",
    "cable": "cabo",
]
